name: Docker Image CI

on:
  push:
    branches: [ "main" ]  # Trigger on push to the main branch
  pull_request:
    branches: [ "main" ]  # Trigger on pull requests to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub (or GitHub Container Registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build the Docker image
        run: |
          IMAGE_NAME="my-image-name"
          VERSION=$(echo $GITHUB_SHA | head -c7) # Use the first 7 chars of the commit hash
          docker build . -f Dockerfile -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest

      # Step 4: Push the Docker image to the registry
      - name: Push the Docker image
        run: |
          IMAGE_NAME="my-image-name"
          VERSION=$(echo $GITHUB_SHA | head -c7)
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest
